---
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  actionlint:
    name: "Linting Actions"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Lint Actions
        uses: raven-actions/actionlint@v2
        with:
          fail-on-error: true
          flags: "-ignore SC2086"
          shellcheck: true

  yamllint:
    name: "Linting YAML"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Lint Actions
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_comment: false
          yamllint_config_filepath: .yamllint.yaml
          yamllint_file_or_dir: .github/workflows
          yamllint_strict: false
